site_title = "MyArxiv"
limit_days = 14
cache_url = "https://Jm20010201.github.io/MyArxiv/cache.json"

[[sources]]
limit = 300
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 300
category = "cs.SY"
title = "Systems and Control"

[[sources]]
limit = 300
category = "math.OC"
title = "Optimization and Control"

[[sources]]
limit = 300
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

# [[sources]]
# limit = 300
# category = "cs.IR"
# title = "Information Retrieval"

# [[sources]]
# limit = 300
# category = "cs.LG"
# title = "Machine Learning"

# [[sources]]
# limit = 300
# category = "cs.MM"
# title = "Multimedia"

# [[sources]]
# limit = 300
# category = "cs.AI"
# title = "Artificial Intelligence"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
